### ISSUE TITLE
Better errors if connections can't be initiated

### ISSUE THREAD

**Issue by reem** [sfackler/r2d2#16]
Right now all one gets is `InitializationError(())` which gives very little information about what could have gone wrong, even if there is an informative error from the connection-opening function.

**Comment by sfackler** [comment]
The errors will be forwarded to the configured [`error handler`](http://sfackler.github.io/r2d2/doc/v0.6.1/r2d2/trait.HandleError.html) where they can be e.g. logged.

We could theoretically forward all of the connection errors to the connection call, but there can be an unbounded amount of them depending on how long the initialization timeout is, and there could even be none.

**Comment by sfackler** [comment]
The next breaking release will have a couple of changes here: The default error handler will log instead of discarding errors, and the last error message will be saved off and put in initialization/get timeout errors: https://github.com/sfackler/r2d2/commit/99b19cc1206c23f760f744c0b8c76c174f5c74cd. It's not the actual error value since the error handler consumes those. We could change it to only get passed a reference to allow them to be stored off, but that seems not super worth it.

**Comment by sfackler** [comment]
Fixed in 0.7.
